// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package querytest

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *MyQueries {
	return &MyQueries{db: db}
}

type MyQueries struct {
	db DBTX
}

func (q *MyQueries) WithTx(tx *sql.Tx) *MyQueries {
	return &MyQueries{
		db: tx,
	}
}
