// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package querytest

import (
	"context"
)

const listBaz = `-- name: ListBaz :many
SELECT id, bar FROM foo
`

func (q *MyQueries) ListBaz(ctx context.Context) ([]Foo, error) {
	rows, err := q.db.QueryContext(ctx, listBaz)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Foo
	for rows.Next() {
		var i Foo
		if err := rows.Scan(&i.ID, &i.Bar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoo = `-- name: ListFoo :many
SELECT id, bar
FROM foo
WHERE id = $1 AND bar = $2
`

type ListFooParams struct {
	ID  int32
	Bar string
}

func (q *MyQueries) ListFoo(ctx context.Context, arg ListFooParams) ([]Foo, error) {
	rows, err := q.db.QueryContext(ctx, listFoo, arg.ID, arg.Bar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Foo
	for rows.Next() {
		var i Foo
		if err := rows.Scan(&i.ID, &i.Bar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
